[package]
edition = "2018"
name = "unit-calculation"
version = "0.1.0"

[dependencies]
colored = "2.0.0"
csv = "1.1"
fancy-regex = "0.8.0"
getopts = "0.2"
itertools = "0.10.3"
regex = "0.1"
serde = {version = "1", features = ["derive"]}
toml = "0.5"
