credit = 125.0

["必須科目"]
credit = 6.0

["必須科目"."線形代数A"]
credit = 2.0
filter = {type = "name", regex = "^線形代数A$"}

["必須科目"."情報数学A"]
credit = 2.0
filter = {type = "name", regex = "^情報数学A$"}

["必須科目"."データサイエンス"]
credit = 6.0
filter = {type = "name", regex = "データサイエンス"}
